import 'dart:convert';

//generated by https://app.quicktype.io/

List<OrderHistory> orderHistoryFromJson(String str) => List<OrderHistory>.from(
    json.decode(str).map((x) => OrderHistory.fromJson(x)));

String orderHistoryToJson(List<OrderHistory> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class OrderHistory {
  OrderHistory({
    this.orderId,
    this.cuurdatetime,
    this.orderNo,
    this.orderAmount,
  });

  String orderId;
  String cuurdatetime;
  String orderNo;
  String orderAmount;

  factory OrderHistory.fromJson(Map<String, dynamic> json) => OrderHistory(
        orderId: json["order_id"],
        cuurdatetime: json["cuurdatetime"],
        orderNo: json["order_no"],
        orderAmount: json["order_amount"],
      );

  Map<String, dynamic> toJson() => {
        "order_id": orderId,
        "cuurdatetime": cuurdatetime,
        "order_no": orderNo,
        "order_amount": orderAmount,
      };
}
