import 'dart:convert';
import 'package:get/get.dart';

//generated by https://app.quicktype.io/

List<OrderHistory> orderHistoryFromJson(String str) => List<OrderHistory>.from(
    json.decode(str).map((x) => OrderHistory.fromJson(x)));

String orderHistoryToJson(List<OrderHistory> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class OrderHistory {
  OrderHistory({
    this.orderId,
    this.orderNo,
    this.orderAmount,
    this.paymentStatus,
    this.placedDate,
    this.dispatchedDate,
    this.deliveredDate,
    this.orderStatus,
  });

  String orderId;
  String orderNo;
  String orderAmount;
  var paymentStatus;
  String placedDate;
  String dispatchedDate;
  String deliveredDate;
  var orderStatus;

  factory OrderHistory.fromJson(Map<String, dynamic> json) {
    String o_status = json["order_status"];
    String pay_status = json["payment_status"];
    return OrderHistory(
      orderId: json["order_id"],
      orderNo: json["order_no"],
      orderAmount: json["order_amount"],
      paymentStatus: pay_status.obs,
      placedDate: json["Placed_Date"],
      dispatchedDate: json["Dispatched_Date"],
      deliveredDate: json["Delivered_Date"],
      orderStatus: o_status.obs,
    );
  }

  Map<String, dynamic> toJson() => {
        "order_id": orderId,
        "order_no": orderNo,
        "order_amount": orderAmount,
        "payment_status": paymentStatus,
        "Placed_Date": placedDate,
        "Dispatched_Date": dispatchedDate,
        "Delivered_Date": deliveredDate,
        "order_status": orderStatus,
      };
}
